### ISSUE TITLE
Pull requests?

### ISSUE THREAD

**Issue by kostyan5** [govex/COVID-19#26]
Will you accept pull request if I add most recent MA data to the CSV?

**Comment by sarabertrandelis** [comment]
Sorry @kostyan5, we need to verify sources on the official State web pages. Is there any official resource we can check? Otherwise, we can also accept private communications with States. If you wish to provide us more updated data, please contact COVID19map@jhu.edu

**Comment by kostyan5** [comment]
I was going to use MA Covid Vaccine Report (https://www.mass.gov/doc/weekly-covid-19-vaccination-report-12-24-2020/download) to update the data. My question is whether you'd allow someone outside your org, like me, to issue a pull request and for you to validate or if the actual change must be made by someone from GOVEX.

**Comment by sarabertrandelis** [comment]
We have that report in our list of sources, and we are now monitoring it for updates daily. I'm afraid the only external contribution we can accept so far is to point us to official sources, but no pull requests from participants outside JHU.
