### ISSUE TITLE
Oklahoma data has a typo

### ISSUE THREAD

**Issue by bathapps** [govex/COVID-19#340]
Line 2519 has an extra "4" in the `people_total_2nd_dose` column that throws it off by a factor of 10.

<img width="441" alt="Screen Shot 2021-02-14 at 3 01 37 PM" src="https://user-images.githubusercontent.com/76496429/107887674-bba25700-6ed5-11eb-83c7-607f4b6f0588.png">

**Comment by sarabertrandelis** [comment]
Thanks @bathapps! We corrected the extra 4 this morning while doing the data update.
