### ISSUE TITLE
Misattribution of source for global vaccinations in JHU Coronavirus Resource Center

### ISSUE THREAD

**Issue by edomt** [govex/COVID-19#342]
Dear CCI team,

Apologies if this isn't the right place to do this, but we could not find any contact information on https://coronavirus.jhu.edu/about and figured you could maybe forward this message to the right person.

There is an [International Vaccination Efforts](https://coronavirus.jhu.edu/vaccines/international) page in the JHU Coronavirus Resource Center that shows a table with vaccinations in all countries in the world. This page credits the Centers for Civic Impact as the source, and notes that "The CRC relies upon publicly available data from multiple sources."

Our understanding (based on this repo) is that the source of this data is actually our dataset of global vaccinations at @OWID, made available here: https://github.com/owid/covid-19-data/tree/master/public/data/vaccinations

If this is indeed the case, would it be possible to correct the source metadata on that page?
Many thanks,

Edouard
Head of Data, _Our World in Data_

**Comment by sarabertrandelis** [comment]
Thank you for raising this issue. We typically link back to the [GitHub](https://github.com/govex/COVID-19/tree/master/data_tables/vaccine_data/global_data) for a list of all sources, but will be updating the specific page in the CRC to reflect Our World in Data as a source.

**Comment by edomt** [comment]
Thank you very much @sarabertrandelis!
