### ISSUE TITLE
Vaccine Data Not Updated Since 3/22

### ISSUE THREAD

**Issue by dje1591** [govex/COVID-19#449]
The Hourly Vaccine Data has not been updated. The last Date is 3/22. Is there an issue with the hourly bot?

**Comment by marycvaughan** [comment]
Good evening @dje1591 -- both the time series and the hourly update have been restored, and you will now see data through 3/24/21.

**Comment by dje1591** [comment]
Is there an issue with the hourly update? The file states updated 19 hours ago. Just trying to understand when 3/25 vaccine data will be available.

**Comment by marycvaughan** [comment]
HI there! You should see the data now @dje1591. Please let us know if you have further questions, thanks!

**Comment by dje1591** [comment]
@marycvaughan Thank you so much! Your hard work is much appreciated!
