### ISSUE TITLE
New Jersey and Guam numbers too high

### ISSUE THREAD

**Issue by bathapps** [govex/COVID-19#454]
In this table:

https://github.com/govex/COVID-19/blob/master/data_tables/vaccine_data/us_data/hourly/vaccine_data_us.csv

The number of stage 1 doses in guam is greater than the population of guam by a lot.

**Comment by dje1591** [comment]
I just checked the NJ Covid Hub and none of the numbers are close to the "All" figures in the table. Can this be corrected?

**Comment by dje1591** [comment]
Looks the data in hourly/vaccine_data_us.csv is now corrected. Thanks!

**Comment by marycvaughan** [comment]
Thank you for flagging this issue! We investigated and corrected the data for 5/2/21 for NJ.
