### ISSUE TITLE
New Jersey Vaccine Numbers Repeated Last 3 Days

### ISSUE THREAD

**Issue by dje1591** [govex/COVID-19#455]
The Vaccine Dose figures for New Jersey have been the same since 5/3. The numbers match what is currently in the hourly file as well.

New Jersey,2021-05-03,All,34.0,US,40.2989,-74.521,,8769895.0,7430120.0,**4634016.0,3005463.0**,"New Jersey, US"
New Jersey,2021-05-04,All,34.0,US,40.2989,-74.521,,8769895.0,7430120.0,**4634016.0,3005463.0**,"New Jersey, US"
New Jersey,2021-05-05,All,34.0,US,40.2989,-74.521,,9006975.0,7430120.0,**4634016.0,3005463.0**,"New Jersey, US"

**Comment by dje1591** [comment]
The JHU dashboard is showing updated figures (https://coronavirus.jhu.edu/vaccines/us-states). When will the bot update the figures in the hourly table?

**Comment by marycvaughan** [comment]
Thank you for flagging this issue! We investigated and corrected the data.
