### ISSUE TITLE
New Jersey first dose data discrepancy May 2nd

### ISSUE THREAD

**Issue by conorotompkins** [govex/COVID-19#458]
The first dose vaccination data for New Jersey doubles on May 2nd 2021 and then goes back to normal after that. Can this be corrected in the source data?

![image](https://user-images.githubusercontent.com/20938344/118270411-08bea680-b48e-11eb-9f90-6d7d64199600.png)

```
  combined_key   date       stage_one_doses
  <chr>          <date>               <dbl>
1 New Jersey, US 2021-05-01         4615887
2 New Jersey, US 2021-05-02         8537206
3 New Jersey, US 2021-05-03         4646283
4 New Jersey, US 2021-05-04         4660766
```

**Comment by marycvaughan** [comment]
Thank you for flagging this issue! We investigated and corrected the data for 5/2/21.
