### ISSUE TITLE
Arkansas finally has a vaccine tracker

### ISSUE THREAD

**Issue by scareduck** [govex/COVID-19#48]
FWIW, the link to Arkansas' vaccine tracker is [here](https://www.healthy.arkansas.gov/programs-services/topics/covid-19-vaccination-plan). They don't appear to grab or store historical data, but at least it's being updated (the [general dashboard](https://experience.arcgis.com/experience/c2ef4a4fcbe5458fbf2e48a21e4fece9) doesn't have this data). Hope that helps.

**Comment by sarabertrandelis** [comment]
@scareduck thanks! We started pulling from that dashboard on 01/07

**Comment by scareduck** [comment]
Hey, thanks for fixing this. Better data is a big deal.
