### ISSUE TITLE
Invalid entry for Tennessee 1/9/2021, line 772

### ISSUE THREAD

**Issue by keithboesel** [govex/COVID-19#74]
The entry for Tennessee on 1/9/2921 has an invalid value for 'people_total_2nd_dose'. It seems like it includes the entry for the previous day, a few spaces, plus the correct value.

01/09/2021,Tennessee,TN,Yes,,,,,328500,,,328500,223791,,,223791,214492,**4561  8364**

**Comment by sarabertrandelis** [comment]
Hi @keithboesel thanks for pointing that out, it was corrected.
