### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by yfarjoun** [govex/COVID-19#87]
Hi folks, just wanted to drop you a thank-you!

I'm using your data here: https://chart-studio.plotly.com/~yfarjoun/3/#/plot

Feel free to close this issue, I just didn't know how else to reach out.

**Comment by yfarjoun** [comment]
happy to make the code public if you like...

**Comment by sarabertrandelis** [comment]
Hi @yfarjoun, really appreciate the comment, and to know that the data is being used, thanks!
